### ISSUE TITLE
Frameless window can not be moved

### ISSUE THREAD

**Issue by dunkelstern** [lassebrenden/electron-netflix#1]
Perhaps recycle the right click as it does nothing in netflix

**Comment by lassebrenden** [comment]
There is actually a (_very_) thin bezel around the window that allows you to move it. It is by no means user-friendly, but it works well enough. Feel free to submit a pull request, though :-)

[Demo](https://media.giphy.com/media/3o7aD8MbOO6okuJiMw/giphy.gif)

[The relevant code is here](https://github.com/lassebrenden/electron-netflix/blob/master/src/main.js#L182-L191):

```js
mainWindow.webContents.on('did-finish-load', () => {
  mainWindow.webContents.insertCSS(`
    html,
    body {
      -webkit-user-select: none;
      -webkit-app-region: drag;
    }
    a {
      -webkit-app-region: no-drag;
    }
  `);
});
```

As you can see, you have to click outside any links (e.g. the Netflix logo) for it to work.

**Comment by lassebrenden** [comment]
[The relevant code is here](https://github.com/lassebrenden/electron-netflix/blob/master/src/main.js#L182-L191):

```js
mainWindow.webContents.on('did-finish-load', () => {
  mainWindow.webContents.insertCSS(`
    html,
    body {
      -webkit-user-select: none;
      -webkit-app-region: drag;
    }
    a {
      -webkit-app-region: no-drag;
    }
  `);
});
```

As you can see, you have to click outside any links (e.g. the Netflix logo) for it to work.
